export type Artwork = {
  id: string;
  src: string;
  thumb: string;
  width: number;
  height: number;
  title: string;
  tag: string;
};
export const kv: Artwork[] = [
  {
    id: 'kv-01',
    src: '/gallery/kv/01.webp',
    thumb: '/gallery/kv/01-thumb.webp',
    width: 1672,
    height: 941,
    title: '让空气也变温柔',
    tag: '慢吞吞日常',
  },
  {
    id: 'kv-02',
    src: '/gallery/kv/02.webp',
    thumb: '/gallery/kv/02-thumb.webp',
    width: 1672,
    height: 941,
    title: '把风收集起来',
    tag: '出门胡闹',
  },
  {
    id: 'kv-03',
    src: '/gallery/kv/03.webp',
    thumb: '/gallery/kv/03-thumb.webp',
    width: 1672,
    height: 941,
    title: '今天适合放空',
    tag: '慢吞吞日常',
  },
  {
    id: 'kv-04',
    src: '/gallery/kv/04.webp',
    thumb: '/gallery/kv/04-thumb.webp',
    width: 1672,
    height: 941,
    title: '今晚月光有电影',
    tag: '夜间营业',
  },
  {
    id: 'kv-05',
    src: '/gallery/kv/05.webp',
    thumb: '/gallery/kv/05-thumb.webp',
    width: 1672,
    height: 941,
    title: '把春天抱回家',
    tag: '出门胡闹',
  },
  {
    id: 'kv-06',
    src: '/gallery/kv/06.webp',
    thumb: '/gallery/kv/06-thumb.webp',
    width: 1672,
    height: 941,
    title: '把星星贴近一点',
    tag: '夜间营业',
  },
  {
    id: 'kv-07',
    src: '/gallery/kv/07.webp',
    thumb: '/gallery/kv/07-thumb.webp',
    width: 1672,
    height: 941,
    title: '面包会替你说早安',
    tag: '慢吞吞日常',
  },
  {
    id: 'kv-08',
    src: '/gallery/kv/08.webp',
    thumb: '/gallery/kv/08-thumb.webp',
    width: 1672,
    height: 941,
    title: '快乐一块块拼好',
    tag: '手作快乐',
  },
  {
    id: 'kv-09',
    src: '/gallery/kv/09.webp',
    thumb: '/gallery/kv/09-thumb.webp',
    width: 1672,
    height: 941,
    title: '在书页里打个盹',
    tag: '慢吞吞日常',
  },
  {
    id: 'kv-10',
    src: '/gallery/kv/10.webp',
    thumb: '/gallery/kv/10-thumb.webp',
    width: 1672,
    height: 941,
    title: '旧时光收藏所',
    tag: '出门胡闹',
  },
  {
    id: 'kv-11',
    src: '/gallery/kv/11.webp',
    thumb: '/gallery/kv/11-thumb.webp',
    width: 1672,
    height: 941,
    title: '今夜一起发光',
    tag: '夜间营业',
  },
  {
    id: 'kv-12',
    src: '/gallery/kv/12.webp',
    thumb: '/gallery/kv/12-thumb.webp',
    width: 1672,
    height: 941,
    title: '和云一起排队',
    tag: '出门胡闹',
  },
  {
    id: 'kv-13',
    src: '/gallery/kv/13.webp',
    thumb: '/gallery/kv/13-thumb.webp',
    width: 1672,
    height: 941,
    title: '泡进暖乎乎的云里',
    tag: '慢吞吞日常',
  },
  {
    id: 'kv-14',
    src: '/gallery/kv/14.webp',
    thumb: '/gallery/kv/14-thumb.webp',
    width: 1672,
    height: 941,
    title: '捏一团好心情',
    tag: '手作快乐',
  },
  {
    id: 'kv-15',
    src: '/gallery/kv/15.webp',
    thumb: '/gallery/kv/15-thumb.webp',
    width: 1672,
    height: 941,
    title: '糖分超载',
    tag: '出门胡闹',
  },
  {
    id: 'kv-16',
    src: '/gallery/kv/16.webp',
    thumb: '/gallery/kv/16-thumb.webp',
    width: 1672,
    height: 941,
    title: '快乐请投币',
    tag: '夜间营业',
  },
  {
    id: 'kv-17',
    src: '/gallery/kv/17.webp',
    thumb: '/gallery/kv/17-thumb.webp',
    width: 1672,
    height: 941,
    title: '把夜晚唱成橙色',
    tag: '夜间营业',
  },
  {
    id: 'kv-18',
    src: '/gallery/kv/18.webp',
    thumb: '/gallery/kv/18-thumb.webp',
    width: 1672,
    height: 941,
    title: '把软乎乎缝回今天',
    tag: '手作快乐',
  },
  {
    id: 'kv-19',
    src: '/gallery/kv/19.webp',
    thumb: '/gallery/kv/19-thumb.webp',
    width: 1672,
    height: 941,
    title: '被窝俱乐部',
    tag: '慢吞吞日常',
  },
  {
    id: 'kv-20',
    src: '/gallery/kv/20.webp',
    thumb: '/gallery/kv/20-thumb.webp',
    width: 1672,
    height: 941,
    title: '把问候寄出去',
    tag: '手作快乐',
  },
  {
    id: 'kv-21',
    src: '/gallery/kv/21.webp',
    thumb: '/gallery/kv/21-thumb.webp',
    width: 1672,
    height: 941,
    title: '让镜头先开心',
    tag: '手作快乐',
  },
];
export const wallpapers: Artwork[] = [
  {
    id: 'wallpapers-01',
    src: '/gallery/wallpapers/01.webp',
    thumb: '/gallery/wallpapers/01-thumb.webp',
    width: 841,
    height: 1870,
    title: '沙发宇宙飞船',
    tag: '软乎日常',
  },
  {
    id: 'wallpapers-02',
    src: '/gallery/wallpapers/02.webp',
    thumb: '/gallery/wallpapers/02-thumb.webp',
    width: 841,
    height: 1870,
    title: '雨天一起踩水',
    tag: '城市漫游',
  },
  {
    id: 'wallpapers-03',
    src: '/gallery/wallpapers/03.webp',
    thumb: '/gallery/wallpapers/03-thumb.webp',
    width: 841,
    height: 1870,
    title: '雨夜出走',
    tag: '城市漫游',
  },
  {
    id: 'wallpapers-04',
    src: '/gallery/wallpapers/04.webp',
    thumb: '/gallery/wallpapers/04-thumb.webp',
    width: 841,
    height: 1870,
    title: '涂鸦墙角',
    tag: '合照涂鸦',
  },
  {
    id: 'wallpapers-05',
    src: '/gallery/wallpapers/05.webp',
    thumb: '/gallery/wallpapers/05-thumb.webp',
    width: 841,
    height: 1870,
    title: '超市推车',
    tag: '城市漫游',
  },
  {
    id: 'wallpapers-06',
    src: '/gallery/wallpapers/06.webp',
    thumb: '/gallery/wallpapers/06-thumb.webp',
    width: 841,
    height: 1870,
    title: '云端被窝',
    tag: '软乎日常',
  },
  {
    id: 'wallpapers-07',
    src: '/gallery/wallpapers/07.webp',
    thumb: '/gallery/wallpapers/07-thumb.webp',
    width: 841,
    height: 1870,
    title: '涂鸦贴贴',
    tag: '合照涂鸦',
  },
  {
    id: 'wallpapers-08',
    src: '/gallery/wallpapers/08.webp',
    thumb: '/gallery/wallpapers/08-thumb.webp',
    width: 841,
    height: 1870,
    title: '抓娃娃现场',
    tag: '快乐游乐场',
  },
  {
    id: 'wallpapers-09',
    src: '/gallery/wallpapers/09.webp',
    thumb: '/gallery/wallpapers/09-thumb.webp',
    width: 841,
    height: 1870,
    title: '扭蛋海洋',
    tag: '快乐游乐场',
  },
  {
    id: 'wallpapers-10',
    src: '/gallery/wallpapers/10.webp',
    thumb: '/gallery/wallpapers/10-thumb.webp',
    width: 841,
    height: 1870,
    title: '合照收藏',
    tag: '合照涂鸦',
  },
  {
    id: 'wallpapers-11',
    src: '/gallery/wallpapers/11.webp',
    thumb: '/gallery/wallpapers/11-thumb.webp',
    width: 841,
    height: 1870,
    title: '透明快乐',
    tag: '快乐游乐场',
  },
  {
    id: 'wallpapers-12',
    src: '/gallery/wallpapers/12.webp',
    thumb: '/gallery/wallpapers/12-thumb.webp',
    width: 841,
    height: 1870,
    title: '唱片慢放',
    tag: '软乎日常',
  },
  {
    id: 'wallpapers-13',
    src: '/gallery/wallpapers/13.webp',
    thumb: '/gallery/wallpapers/13-thumb.webp',
    width: 841,
    height: 1870,
    title: '泡泡浴',
    tag: '软乎日常',
  },
  {
    id: 'wallpapers-14',
    src: '/gallery/wallpapers/14.webp',
    thumb: '/gallery/wallpapers/14-thumb.webp',
    width: 841,
    height: 1870,
    title: '随身出逃',
    tag: '城市漫游',
  },
  {
    id: 'wallpapers-15',
    src: '/gallery/wallpapers/15.webp',
    thumb: '/gallery/wallpapers/15-thumb.webp',
    width: 841,
    height: 1870,
    title: '拍立得小队',
    tag: '合照涂鸦',
  },
  {
    id: 'wallpapers-16',
    src: '/gallery/wallpapers/16.webp',
    thumb: '/gallery/wallpapers/16-thumb.webp',
    width: 841,
    height: 1870,
    title: '便利店夜班',
    tag: '城市漫游',
  },
  {
    id: 'wallpapers-17',
    src: '/gallery/wallpapers/17.webp',
    thumb: '/gallery/wallpapers/17-thumb.webp',
    width: 841,
    height: 1870,
    title: '游戏厅搭子',
    tag: '快乐游乐场',
  },
  {
    id: 'wallpapers-18',
    src: '/gallery/wallpapers/18.webp',
    thumb: '/gallery/wallpapers/18-thumb.webp',
    width: 841,
    height: 1870,
    title: '日落牵手',
    tag: '城市漫游',
  },
  {
    id: 'wallpapers-19',
    src: '/gallery/wallpapers/19.webp',
    thumb: '/gallery/wallpapers/19-thumb.webp',
    width: 841,
    height: 1870,
    title: '被窝小星球',
    tag: '软乎日常',
  },
  {
    id: 'wallpapers-20',
    src: '/gallery/wallpapers/20.webp',
    thumb: '/gallery/wallpapers/20-thumb.webp',
    width: 841,
    height: 1870,
    title: '音乐现场',
    tag: '快乐游乐场',
  },
  {
    id: 'wallpapers-21',
    src: '/gallery/wallpapers/21.webp',
    thumb: '/gallery/wallpapers/21-thumb.webp',
    width: 841,
    height: 1870,
    title: '饼干野餐',
    tag: '软乎日常',
  },
  {
    id: 'wallpapers-22',
    src: '/gallery/wallpapers/22.webp',
    thumb: '/gallery/wallpapers/22-thumb.webp',
    width: 841,
    height: 1870,
    title: '天台晚安',
    tag: '软乎日常',
  },
  {
    id: 'wallpapers-23',
    src: '/gallery/wallpapers/23.webp',
    thumb: '/gallery/wallpapers/23-thumb.webp',
    width: 841,
    height: 1870,
    title: '洗衣日',
    tag: '软乎日常',
  },
  {
    id: 'wallpapers-24',
    src: '/gallery/wallpapers/24.webp',
    thumb: '/gallery/wallpapers/24-thumb.webp',
    width: 841,
    height: 1870,
    title: '口袋里的你',
    tag: '软乎日常',
  },
];
export const festivals: Artwork[] = [
  {
    id: 'festival-3',
    src: '/gallery/festivals/03.webp',
    thumb: '/gallery/festivals/03-thumb.webp',
    width: 1536,
    height: 1024,
    title: '春日慢吞吞',
    tag: '春日',
  },
  {
    id: 'festival-14',
    src: '/gallery/festivals/14.webp',
    thumb: '/gallery/festivals/14-thumb.webp',
    width: 1536,
    height: 1024,
    title: '雨落春芽，想念有声',
    tag: '春日',
  },
  {
    id: 'festival-23',
    src: '/gallery/festivals/23.webp',
    thumb: '/gallery/festivals/23-thumb.webp',
    width: 1536,
    height: 1024,
    title: '把春天捎进相册',
    tag: '春日',
  },
  {
    id: 'festival-51',
    src: '/gallery/festivals/51.webp',
    thumb: '/gallery/festivals/51-thumb.webp',
    width: 1536,
    height: 1024,
    title: '春风从头开始',
    tag: '春日',
  },
  {
    id: 'festival-24',
    src: '/gallery/festivals/24.webp',
    thumb: '/gallery/festivals/24-thumb.webp',
    width: 1536,
    height: 1024,
    title: '把月光留给想见的人',
    tag: '团圆',
  },
  {
    id: 'festival-34',
    src: '/gallery/festivals/34.webp',
    thumb: '/gallery/festivals/34-thumb.webp',
    width: 1536,
    height: 1024,
    title: '今晚月色替我说想你',
    tag: '团圆',
  },
  {
    id: 'festival-15',
    src: '/gallery/festivals/15.webp',
    thumb: '/gallery/festivals/15-thumb.webp',
    width: 1536,
    height: 1024,
    title: '灯火归心',
    tag: '新春',
  },
  {
    id: 'festival-22',
    src: '/gallery/festivals/22.webp',
    thumb: '/gallery/festivals/22-thumb.webp',
    width: 1536,
    height: 1024,
    title: '把圆满捧在手心',
    tag: '新春',
  },
  {
    id: 'festival-38',
    src: '/gallery/festivals/38.webp',
    thumb: '/gallery/festivals/38-thumb.webp',
    width: 1536,
    height: 1024,
    title: '灯火年年，人间团圆',
    tag: '新春',
  },
  {
    id: 'festival-39',
    src: '/gallery/festivals/39.webp',
    thumb: '/gallery/festivals/39-thumb.webp',
    width: 1536,
    height: 1024,
    title: '小火慢煮的是牵挂',
    tag: '新春',
  },
  {
    id: 'festival-41',
    src: '/gallery/festivals/41.webp',
    thumb: '/gallery/festivals/41-thumb.webp',
    width: 1536,
    height: 1024,
    title: '把烟火暖到心坎里',
    tag: '新春',
  },
  {
    id: 'festival-52',
    src: '/gallery/festivals/52.webp',
    thumb: '/gallery/festivals/52-thumb.webp',
    width: 1536,
    height: 1024,
    title: '把日子贴进生活里',
    tag: '新春',
  },
  {
    id: 'festival-18',
    src: '/gallery/festivals/18.webp',
    thumb: '/gallery/festivals/18-thumb.webp',
    width: 1536,
    height: 1024,
    title: '把热气端上冬天的桌',
    tag: '暖冬',
  },
  {
    id: 'festival-49',
    src: '/gallery/festivals/49.webp',
    thumb: '/gallery/festivals/49-thumb.webp',
    width: 1536,
    height: 1024,
    title: '把远山走成思念',
    tag: '秋游',
  },
];
